### ISSUE TITLE
Discontinuation of Project Elixir? 

### ISSUE THREAD

**Issue by owl4ce** [ImKKingshuk/Awesome-CustomROM#1]
Hi! I just found this great curated repository. I was surprised that development of Project Elixir was halted due to its developer scandal. Any status change for this? I hope you confirm it.

[1] https://xdaforums.com/t/elixiros-to-break-and-wipe-your-device.4672456/
[2] https://reddit.com/r/Android/comments/1cuzvg6/to_my_fellow_android_custom_rom_enthusiasts_i/

It was a great ROM, I use it for long-term, but somehow its developer make a fatal mistake that unethical.

**Comment by ImKKingshuk** [comment]
But the team still updating their repos, they updating their codes and pushing changes for different repos everyday, the last commit they made was just 1 hour ago, so I don't think they discontinued the Project, may be the team facing some issues like time management etc.. they pushing changes to their GitHub repos, means its not dead... 
Project Elixir still Active.

**Comment by uzzy-buzzy** [comment]
yes it is still active, i just checked the redmi note 9s repo on their website
