### ISSUE TITLE
crawler ROM

### ISSUE THREAD

**Issue by ghost** [ImKKingshuk/Awesome-CustomROM#2]
You can crawler https://www.pling.com/browse?cat=495&ord=latest More than 3000 ROM

**Comment by ImKKingshuk** [comment]
They are not different CustomROMs, they're rom files, the list is all about rom devices, if a Rom (pixel experience, project elixir etc) supports 50 devices & 50 rom files available of that rom, that doesn't mean 50 CustomROMs, thats a singleROM...
