### ISSUE TITLE
Wrong hyperlink for Project Elixir

### ISSUE THREAD

**Issue by javadzarezadeh** [ImKKingshuk/Awesome-CustomROM#3]
Hi buddy,

Thanks for your great list. It seems that the hyperlink for the Project Elixir is wrong, and you put the Project Matrixx instead.

Moreover I wanted to ask, Since the Pixel Experience is discontinued, which one of these recommended ROMs is like Pixel Experience in unlimited Google Photos backup storage?

**Comment by ImKKingshuk** [comment]
check out PixelOS, Paranoid Android these two roms same as Pixel Experience.
